title: Seven Concepts Media
description: "Print-on-demand books." 
theme: Minima

# Custom navbar links
header_links:

  - title: Available Book Descriptions
    url: /books/
  - title: About Us
    url: /about/
