title: Seven Concepts Media
"Branch of KJ7Concepts LLC"
description: "Print-on-demand books." 
"We never run out."
theme: minima

# Custom navbar links
header_links:
  - title: Home
    url: /
  - title: Book Descriptions
    url: /books/
  - title: About
    url: /about/
