name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v3

      # 2. Set up Ruby (needed for Jekyll)
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'

      # 3. Install dependencies
      - run: bundle install

      # 4. Build the site with Jekyll into _site
      - run: bundle exec jekyll build --destination _site

      # 5. Deploy to GitHub Pages via peaceiris
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
